<a href="https://colab.research.google.com/github/Benjamin5555/DirectedPercolation/blob/master/Efficient_periodic_boundary_conditions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import math
from time import time

In [2]:
N = 12



In [3]:
start = time()
precalcA = np.zeros((N,N))
for i in range(0,N):
    for j in range(0,N):
        ij = abs(i-j)
        if (ij <=N/2):
                precalcA[i][j] =ij
        elif(i>j):
            precalcA[i][j] = N-i+j
        elif(i<=j):
            precalcA[i][j]= N-j+i

print(time()-start)
print(precalcA)


0.0006825923919677734
[[0. 1. 2. 3. 4. 5. 6. 5. 4. 3. 2. 1.]
 [1. 0. 1. 2. 3. 4. 5. 6. 5. 4. 3. 2.]
 [2. 1. 0. 1. 2. 3. 4. 5. 6. 5. 4. 3.]
 [3. 2. 1. 0. 1. 2. 3. 4. 5. 6. 5. 4.]
 [4. 3. 2. 1. 0. 1. 2. 3. 4. 5. 6. 5.]
 [5. 4. 3. 2. 1. 0. 1. 2. 3. 4. 5. 6.]
 [6. 5. 4. 3. 2. 1. 0. 1. 2. 3. 4. 5.]
 [5. 6. 5. 4. 3. 2. 1. 0. 1. 2. 3. 4.]
 [4. 5. 6. 5. 4. 3. 2. 1. 0. 1. 2. 3.]
 [3. 4. 5. 6. 5. 4. 3. 2. 1. 0. 1. 2.]
 [2. 3. 4. 5. 6. 5. 4. 3. 2. 1. 0. 1.]
 [1. 2. 3. 4. 5. 6. 5. 4. 3. 2. 1. 0.]]


In [4]:
start = time()
precalcB = np.zeros((N,N))
for i in range(0,N):
    j=0
    while(j<i):
        ij = abs(i-j)
        if (ij <=N/2):
                precalcB[i][j] =ij
        elif(i>j):
            precalcB[i][j] = N-i+j
        elif(i<=j):
            precalcB[i][j]= N-j+i
        j=j+1

for i in range(0,N):
    for j in range(i,N):
        precalcB[i][j] =precalcB[j][i]
    
print(time()-start)
print(precalcB)

0.00035572052001953125
[[0. 1. 2. 3. 4. 5. 6. 5. 4. 3. 2. 1.]
 [1. 0. 1. 2. 3. 4. 5. 6. 5. 4. 3. 2.]
 [2. 1. 0. 1. 2. 3. 4. 5. 6. 5. 4. 3.]
 [3. 2. 1. 0. 1. 2. 3. 4. 5. 6. 5. 4.]
 [4. 3. 2. 1. 0. 1. 2. 3. 4. 5. 6. 5.]
 [5. 4. 3. 2. 1. 0. 1. 2. 3. 4. 5. 6.]
 [6. 5. 4. 3. 2. 1. 0. 1. 2. 3. 4. 5.]
 [5. 6. 5. 4. 3. 2. 1. 0. 1. 2. 3. 4.]
 [4. 5. 6. 5. 4. 3. 2. 1. 0. 1. 2. 3.]
 [3. 4. 5. 6. 5. 4. 3. 2. 1. 0. 1. 2.]
 [2. 3. 4. 5. 6. 5. 4. 3. 2. 1. 0. 1.]
 [1. 2. 3. 4. 5. 6. 5. 4. 3. 2. 1. 0.]]


In [5]:
(precalcA == precalcB).all()

True

# Flat version

In [6]:
def fLen(k):
    return int(k*(k+1)/2)

def arrToFlat(i,j):
    """
https://www.geeksforgeeks.org/convert-given-lower-triangular-matrix-to-1d-array/
    """
    if i>=j:
        return int(((i+1)*i)/2+j)
    else:
        return int(((j+1)*j)/2+i)



pcF = np.ones(arrToFlat(N,N))
#print(pcF)

for i in range(0,N):
    j=0
    while(j<=i):
        
        ij = abs(i-j)

        if (ij <=N/2):
            pcF[arrToFlat(i,j)]= ij
        elif(ij>N/2):
            print(i,j,arrToFlat(i,j),N-i+j)
            pcF[arrToFlat(i,j)]= N-i+j
        #print(i,j,pcF[i+j])
        j=j+1


print(pcF)

def a_pcF(i,j):
    if(i>j):
        return pcF[arrToFlat(i,j)]
    else:
         return pcF[arrToFlat(j,i)]

7 0 28 5
8 0 36 4
8 1 37 5
9 0 45 3
9 1 46 4
9 2 47 5
10 0 55 2
10 1 56 3
10 2 57 4
10 3 58 5
11 0 66 1
11 1 67 2
11 2 68 3
11 3 69 4
11 4 70 5
[0. 1. 0. 2. 1. 0. 3. 2. 1. 0. 4. 3. 2. 1. 0. 5. 4. 3. 2. 1. 0. 6. 5. 4.
 3. 2. 1. 0. 5. 6. 5. 4. 3. 2. 1. 0. 4. 5. 6. 5. 4. 3. 2. 1. 0. 3. 4. 5.
 6. 5. 4. 3. 2. 1. 0. 2. 3. 4. 5. 6. 5. 4. 3. 2. 1. 0. 1. 2. 3. 4. 5. 6.
 5. 4. 3. 2. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [7]:
start = time()
precalcC = np.zeros((N,N))
for i in range(0,N):
    for j in range(0,N):
       # print((i,j))
        precalcC[i][j] = a_pcF(i,j)

print(time()-start)
print(precalcC)
print(precalcB)
print(precalcC - precalcB)

0.0005280971527099609
[[0. 1. 2. 3. 4. 5. 6. 5. 4. 3. 2. 1.]
 [1. 0. 1. 2. 3. 4. 5. 6. 5. 4. 3. 2.]
 [2. 1. 0. 1. 2. 3. 4. 5. 6. 5. 4. 3.]
 [3. 2. 1. 0. 1. 2. 3. 4. 5. 6. 5. 4.]
 [4. 3. 2. 1. 0. 1. 2. 3. 4. 5. 6. 5.]
 [5. 4. 3. 2. 1. 0. 1. 2. 3. 4. 5. 6.]
 [6. 5. 4. 3. 2. 1. 0. 1. 2. 3. 4. 5.]
 [5. 6. 5. 4. 3. 2. 1. 0. 1. 2. 3. 4.]
 [4. 5. 6. 5. 4. 3. 2. 1. 0. 1. 2. 3.]
 [3. 4. 5. 6. 5. 4. 3. 2. 1. 0. 1. 2.]
 [2. 3. 4. 5. 6. 5. 4. 3. 2. 1. 0. 1.]
 [1. 2. 3. 4. 5. 6. 5. 4. 3. 2. 1. 0.]]
[[0. 1. 2. 3. 4. 5. 6. 5. 4. 3. 2. 1.]
 [1. 0. 1. 2. 3. 4. 5. 6. 5. 4. 3. 2.]
 [2. 1. 0. 1. 2. 3. 4. 5. 6. 5. 4. 3.]
 [3. 2. 1. 0. 1. 2. 3. 4. 5. 6. 5. 4.]
 [4. 3. 2. 1. 0. 1. 2. 3. 4. 5. 6. 5.]
 [5. 4. 3. 2. 1. 0. 1. 2. 3. 4. 5. 6.]
 [6. 5. 4. 3. 2. 1. 0. 1. 2. 3. 4. 5.]
 [5. 6. 5. 4. 3. 2. 1. 0. 1. 2. 3. 4.]
 [4. 5. 6. 5. 4. 3. 2. 1. 0. 1. 2. 3.]
 [3. 4. 5. 6. 5. 4. 3. 2. 1. 0. 1. 2.]
 [2. 3. 4. 5. 6. 5. 4. 3. 2. 1. 0. 1.]
 [1. 2. 3. 4. 5. 6. 5. 4. 3. 2. 1. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 

In [8]:

# for  i in range(math.ceil(N/2)):
#     print(i)

# for i in range(math.ceil(N/2),N):
#     print(N-i)

precalcS = []
for i in range(N):
    if(i<N/2):
        print(i,i)
        precalcS.append(i)
    else:
        print(i,N-i)
        precalcS.append(N-i)

0 0
1 1
2 2
3 3
4 4
5 5
6 6
7 5
8 4
9 3
10 2
11 1


In [9]:
def access_array(i,j):
    return precalcS[i-j-N*int(2*(i-j)/N)]


In [10]:
fullTestS = np.ones((N,N))*-1

for i in range(N):
    for j in range(N):
        
        fullTestS[i][j] = access_array(i,j)

In [11]:
print(fullTestS)
print(precalcA)

[[0. 1. 2. 3. 4. 5. 6. 5. 4. 3. 2. 1.]
 [1. 0. 1. 2. 3. 4. 5. 6. 5. 4. 3. 2.]
 [2. 1. 0. 1. 2. 3. 4. 5. 6. 5. 4. 3.]
 [3. 2. 1. 0. 1. 2. 3. 4. 5. 6. 5. 4.]
 [4. 3. 2. 1. 0. 1. 2. 3. 4. 5. 6. 5.]
 [5. 4. 3. 2. 1. 0. 1. 2. 3. 4. 5. 6.]
 [6. 5. 4. 3. 2. 1. 0. 1. 2. 3. 4. 5.]
 [5. 6. 5. 4. 3. 2. 1. 0. 1. 2. 3. 4.]
 [4. 5. 6. 5. 4. 3. 2. 1. 0. 1. 2. 3.]
 [3. 4. 5. 6. 5. 4. 3. 2. 1. 0. 1. 2.]
 [2. 3. 4. 5. 6. 5. 4. 3. 2. 1. 0. 1.]
 [1. 2. 3. 4. 5. 6. 5. 4. 3. 2. 1. 0.]]
[[0. 1. 2. 3. 4. 5. 6. 5. 4. 3. 2. 1.]
 [1. 0. 1. 2. 3. 4. 5. 6. 5. 4. 3. 2.]
 [2. 1. 0. 1. 2. 3. 4. 5. 6. 5. 4. 3.]
 [3. 2. 1. 0. 1. 2. 3. 4. 5. 6. 5. 4.]
 [4. 3. 2. 1. 0. 1. 2. 3. 4. 5. 6. 5.]
 [5. 4. 3. 2. 1. 0. 1. 2. 3. 4. 5. 6.]
 [6. 5. 4. 3. 2. 1. 0. 1. 2. 3. 4. 5.]
 [5. 6. 5. 4. 3. 2. 1. 0. 1. 2. 3. 4.]
 [4. 5. 6. 5. 4. 3. 2. 1. 0. 1. 2. 3.]
 [3. 4. 5. 6. 5. 4. 3. 2. 1. 0. 1. 2.]
 [2. 3. 4. 5. 6. 5. 4. 3. 2. 1. 0. 1.]
 [1. 2. 3. 4. 5. 6. 5. 4. 3. 2. 1. 0.]]


In [13]:

print((precalcA==fullTestS).all())
print((fullTestS==precalcB).all())
print((fullTestS==precalcC).all())

True
True
True
