<a href="https://colab.research.google.com/github/Benjamin5555/DirectedPercolation/blob/master/Efficient_periodic_boundary_conditions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from time import time

In [ ]:
N = 10



In [ ]:
start = time()
precalcA = np.zeros((N,N))
for i in range(0,N):
    for j in range(0,N):
        ij = abs(i-j)
        if (ij <=N/2):
                precalcA[i][j] =ij
        elif(i>j):
            precalcA[i][j] = N-i+j
        elif(i<=j):
            precalcA[i][j]= N-j+i

print(time()-start)
print(precalcA)


0.0008988380432128906
[[0. 1. 2. 3. 4. 5. 4. 3. 2. 1.]
 [1. 0. 1. 2. 3. 4. 5. 4. 3. 2.]
 [2. 1. 0. 1. 2. 3. 4. 5. 4. 3.]
 [3. 2. 1. 0. 1. 2. 3. 4. 5. 4.]
 [4. 3. 2. 1. 0. 1. 2. 3. 4. 5.]
 [5. 4. 3. 2. 1. 0. 1. 2. 3. 4.]
 [4. 5. 4. 3. 2. 1. 0. 1. 2. 3.]
 [3. 4. 5. 4. 3. 2. 1. 0. 1. 2.]
 [2. 3. 4. 5. 4. 3. 2. 1. 0. 1.]
 [1. 2. 3. 4. 5. 4. 3. 2. 1. 0.]]


In [ ]:
start = time()
precalcB = np.zeros((N,N))
for i in range(0,N):
    j=0
    while(j<i):
        ij = abs(i-j)
        if (ij <=N/2):
                precalcB[i][j] =ij
        elif(i>j):
            precalcB[i][j] = N-i+j
        elif(i<=j):
            precalcB[i][j]= N-j+i
        j=j+1

for i in range(0,N):
    for j in range(i,N):
        precalcB[i][j] =precalcB[j][i]
    
print(time()-start)
print(precalcB)

0.00027489662170410156
[[0. 1. 2. 3. 4. 5. 4. 3. 2. 1.]
 [1. 0. 1. 2. 3. 4. 5. 4. 3. 2.]
 [2. 1. 0. 1. 2. 3. 4. 5. 4. 3.]
 [3. 2. 1. 0. 1. 2. 3. 4. 5. 4.]
 [4. 3. 2. 1. 0. 1. 2. 3. 4. 5.]
 [5. 4. 3. 2. 1. 0. 1. 2. 3. 4.]
 [4. 5. 4. 3. 2. 1. 0. 1. 2. 3.]
 [3. 4. 5. 4. 3. 2. 1. 0. 1. 2.]
 [2. 3. 4. 5. 4. 3. 2. 1. 0. 1.]
 [1. 2. 3. 4. 5. 4. 3. 2. 1. 0.]]


In [ ]:
(precalcA == precalcB).all()

True

# Flat version

In [1]:
def fLen(k):
    return int(k*(k+1)/2)

def arrToFlat(i,j):
    """
https://www.geeksforgeeks.org/convert-given-lower-triangular-matrix-to-1d-array/
    """
    if i>=j:
        return int(((i+1)*i)/2+j)
    else:
        return int(((j+1)*j)/2+i)



pcF = np.ones(arrToFlat(N,N))
#print(pcF)

for i in range(0,N):
    j=0
    while(j<=i):
        
        ij = abs(i-j)

        if (ij <=N/2):
            pcF[arrToFlat(i,j)]= ij
        elif(ij>N/2):
            print(i,j,arrToFlat(i,j),N-i+j)
            pcF[arrToFlat(i,j)]= N-i+j
        #print(i,j,pcF[i+j])
        j=j+1


print(pcF)

def a_pcF(i,j):
    if(i>j):
        return pcF[arrToFlat(i,j)]
    else:
         return pcF[arrToFlat(j,i)]

NameError: ignored

In [ ]:
start = time()
precalcC = np.zeros((N,N))
for i in range(0,N):
    for j in range(0,N):
       # print((i,j))
        precalcC[i][j] = a_pcF(i,j)

print(time()-start)
print(precalcC)
print(precalcB)
print(precalcC - precalcB)

0.0003390312194824219
[[0. 1. 2. 3. 4. 5. 4. 3. 2. 1.]
 [1. 0. 1. 2. 3. 4. 5. 4. 3. 2.]
 [2. 1. 0. 1. 2. 3. 4. 5. 4. 3.]
 [3. 2. 1. 0. 1. 2. 3. 4. 5. 4.]
 [4. 3. 2. 1. 0. 1. 2. 3. 4. 5.]
 [5. 4. 3. 2. 1. 0. 1. 2. 3. 4.]
 [4. 5. 4. 3. 2. 1. 0. 1. 2. 3.]
 [3. 4. 5. 4. 3. 2. 1. 0. 1. 2.]
 [2. 3. 4. 5. 4. 3. 2. 1. 0. 1.]
 [1. 2. 3. 4. 5. 4. 3. 2. 1. 0.]]
[[0. 1. 2. 3. 4. 5. 4. 3. 2. 1.]
 [1. 0. 1. 2. 3. 4. 5. 4. 3. 2.]
 [2. 1. 0. 1. 2. 3. 4. 5. 4. 3.]
 [3. 2. 1. 0. 1. 2. 3. 4. 5. 4.]
 [4. 3. 2. 1. 0. 1. 2. 3. 4. 5.]
 [5. 4. 3. 2. 1. 0. 1. 2. 3. 4.]
 [4. 5. 4. 3. 2. 1. 0. 1. 2. 3.]
 [3. 4. 5. 4. 3. 2. 1. 0. 1. 2.]
 [2. 3. 4. 5. 4. 3. 2. 1. 0. 1.]
 [1. 2. 3. 4. 5. 4. 3. 2. 1. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.

False
