<a href="https://colab.research.google.com/github/Benjamin5555/DirectedPercolation/blob/master/Efficient_periodic_boundary_conditions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import math
from time import time

In [2]:
N = 10



In [3]:
start = time()
precalcA = np.zeros((N,N))
for i in range(0,N):
    for j in range(0,N):
        ij = abs(i-j)
        if (ij <=N/2):
                precalcA[i][j] =ij
        elif(i>j):
            precalcA[i][j] = N-i+j
        elif(i<=j):
            precalcA[i][j]= N-j+i

print(time()-start)
print(precalcA)


0.0006043910980224609
[[0. 1. 2. 3. 4. 5. 4. 3. 2. 1.]
 [1. 0. 1. 2. 3. 4. 5. 4. 3. 2.]
 [2. 1. 0. 1. 2. 3. 4. 5. 4. 3.]
 [3. 2. 1. 0. 1. 2. 3. 4. 5. 4.]
 [4. 3. 2. 1. 0. 1. 2. 3. 4. 5.]
 [5. 4. 3. 2. 1. 0. 1. 2. 3. 4.]
 [4. 5. 4. 3. 2. 1. 0. 1. 2. 3.]
 [3. 4. 5. 4. 3. 2. 1. 0. 1. 2.]
 [2. 3. 4. 5. 4. 3. 2. 1. 0. 1.]
 [1. 2. 3. 4. 5. 4. 3. 2. 1. 0.]]


In [4]:
start = time()
precalcB = np.zeros((N,N))
for i in range(0,N):
    j=0
    while(j<i):
        ij = abs(i-j)
        if (ij <=N/2):
                precalcB[i][j] =ij
        elif(i>j):
            precalcB[i][j] = N-i+j
        elif(i<=j):
            precalcB[i][j]= N-j+i
        j=j+1

for i in range(0,N):
    for j in range(i,N):
        precalcB[i][j] =precalcB[j][i]
    
print(time()-start)
print(precalcB)

0.00031757354736328125
[[0. 1. 2. 3. 4. 5. 4. 3. 2. 1.]
 [1. 0. 1. 2. 3. 4. 5. 4. 3. 2.]
 [2. 1. 0. 1. 2. 3. 4. 5. 4. 3.]
 [3. 2. 1. 0. 1. 2. 3. 4. 5. 4.]
 [4. 3. 2. 1. 0. 1. 2. 3. 4. 5.]
 [5. 4. 3. 2. 1. 0. 1. 2. 3. 4.]
 [4. 5. 4. 3. 2. 1. 0. 1. 2. 3.]
 [3. 4. 5. 4. 3. 2. 1. 0. 1. 2.]
 [2. 3. 4. 5. 4. 3. 2. 1. 0. 1.]
 [1. 2. 3. 4. 5. 4. 3. 2. 1. 0.]]


In [5]:
(precalcA == precalcB).all()

True

# Flat version

In [6]:
def fLen(k):
    return int(k*(k+1)/2)

def arrToFlat(i,j):
    """
https://www.geeksforgeeks.org/convert-given-lower-triangular-matrix-to-1d-array/
    """
    if i>=j:
        return int(((i+1)*i)/2+j)
    else:
        return int(((j+1)*j)/2+i)



pcF = np.ones(arrToFlat(N,N))
#print(pcF)

for i in range(0,N):
    j=0
    while(j<=i):
        
        ij = abs(i-j)

        if (ij <=N/2):
            pcF[arrToFlat(i,j)]= ij
        elif(ij>N/2):
            print(i,j,arrToFlat(i,j),N-i+j)
            pcF[arrToFlat(i,j)]= N-i+j
        #print(i,j,pcF[i+j])
        j=j+1


print(pcF)

def a_pcF(i,j):
    if(i>j):
        return pcF[arrToFlat(i,j)]
    else:
         return pcF[arrToFlat(j,i)]

6 0 21 4
7 0 28 3
7 1 29 4
8 0 36 2
8 1 37 3
8 2 38 4
9 0 45 1
9 1 46 2
9 2 47 3
9 3 48 4
[0. 1. 0. 2. 1. 0. 3. 2. 1. 0. 4. 3. 2. 1. 0. 5. 4. 3. 2. 1. 0. 4. 5. 4.
 3. 2. 1. 0. 3. 4. 5. 4. 3. 2. 1. 0. 2. 3. 4. 5. 4. 3. 2. 1. 0. 1. 2. 3.
 4. 5. 4. 3. 2. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [7]:
start = time()
precalcC = np.zeros((N,N))
for i in range(0,N):
    for j in range(0,N):
       # print((i,j))
        precalcC[i][j] = a_pcF(i,j)

print(time()-start)
print(precalcC)
print(precalcB)
print(precalcC - precalcB)

0.0005629062652587891
[[0. 1. 2. 3. 4. 5. 4. 3. 2. 1.]
 [1. 0. 1. 2. 3. 4. 5. 4. 3. 2.]
 [2. 1. 0. 1. 2. 3. 4. 5. 4. 3.]
 [3. 2. 1. 0. 1. 2. 3. 4. 5. 4.]
 [4. 3. 2. 1. 0. 1. 2. 3. 4. 5.]
 [5. 4. 3. 2. 1. 0. 1. 2. 3. 4.]
 [4. 5. 4. 3. 2. 1. 0. 1. 2. 3.]
 [3. 4. 5. 4. 3. 2. 1. 0. 1. 2.]
 [2. 3. 4. 5. 4. 3. 2. 1. 0. 1.]
 [1. 2. 3. 4. 5. 4. 3. 2. 1. 0.]]
[[0. 1. 2. 3. 4. 5. 4. 3. 2. 1.]
 [1. 0. 1. 2. 3. 4. 5. 4. 3. 2.]
 [2. 1. 0. 1. 2. 3. 4. 5. 4. 3.]
 [3. 2. 1. 0. 1. 2. 3. 4. 5. 4.]
 [4. 3. 2. 1. 0. 1. 2. 3. 4. 5.]
 [5. 4. 3. 2. 1. 0. 1. 2. 3. 4.]
 [4. 5. 4. 3. 2. 1. 0. 1. 2. 3.]
 [3. 4. 5. 4. 3. 2. 1. 0. 1. 2.]
 [2. 3. 4. 5. 4. 3. 2. 1. 0. 1.]
 [1. 2. 3. 4. 5. 4. 3. 2. 1. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.

In [76]:

# for  i in range(math.ceil(N/2)):
#     print(i)

# for i in range(math.ceil(N/2),N):
#     print(N-i)

precalcS = []
for i in range(N):
    if(i<N/2):
        print(i,i)
        precalcS.append(i)
    else:
        print(i,N-i)
        precalcS.append(N-i)

0 0
1 1
2 2
3 3
4 4
5 5
6 4
7 3
8 2
9 1


In [81]:
def index2Dto1D(i,j):
    
     return abs(i-j-N*int(2*(i-j)/N))


def access_array(i,j):
    # print(index2Dto1D(i,j))
    # return precalcS[index2Dto1D(i,j)]

    
        # return index2Dto1D(i,j)
        return precalcS[index2Dto1D(i,j)]



In [82]:
fullTestS = np.ones((N,N))*-1

for i in range(N):
    for j in range(N):
        print(i,j," ", end="")
        print(index2Dto1D(i,j))
        fullTestS[i][j] = access_array(i,j)



0 0  0
0 1  1
0 2  2
0 3  3
0 4  4
0 5  5
0 6  4
0 7  3
0 8  2
0 9  1
1 0  1
1 1  0
1 2  1
1 3  2
1 4  3
1 5  4
1 6  5
1 7  4
1 8  3
1 9  2
2 0  2
2 1  1
2 2  0
2 3  1
2 4  2
2 5  3
2 6  4
2 7  5
2 8  4
2 9  3
3 0  3
3 1  2
3 2  1
3 3  0
3 4  1
3 5  2
3 6  3
3 7  4
3 8  5
3 9  4
4 0  4
4 1  3
4 2  2
4 3  1
4 4  0
4 5  1
4 6  2
4 7  3
4 8  4
4 9  5
5 0  5
5 1  4
5 2  3
5 3  2
5 4  1
5 5  0
5 6  1
5 7  2
5 8  3
5 9  4
6 0  4
6 1  5
6 2  4
6 3  3
6 4  2
6 5  1
6 6  0
6 7  1
6 8  2
6 9  3
7 0  3
7 1  4
7 2  5
7 3  4
7 4  3
7 5  2
7 6  1
7 7  0
7 8  1
7 9  2
8 0  2
8 1  3
8 2  4
8 3  5
8 4  4
8 5  3
8 6  2
8 7  1
8 8  0
8 9  1
9 0  1
9 1  2
9 2  3
9 3  4
9 4  5
9 5  4
9 6  3
9 7  2
9 8  1
9 9  0


In [83]:
print(fullTestS)
print(precalcA)

[[0. 1. 2. 3. 4. 5. 4. 3. 2. 1.]
 [1. 0. 1. 2. 3. 4. 5. 4. 3. 2.]
 [2. 1. 0. 1. 2. 3. 4. 5. 4. 3.]
 [3. 2. 1. 0. 1. 2. 3. 4. 5. 4.]
 [4. 3. 2. 1. 0. 1. 2. 3. 4. 5.]
 [5. 4. 3. 2. 1. 0. 1. 2. 3. 4.]
 [4. 5. 4. 3. 2. 1. 0. 1. 2. 3.]
 [3. 4. 5. 4. 3. 2. 1. 0. 1. 2.]
 [2. 3. 4. 5. 4. 3. 2. 1. 0. 1.]
 [1. 2. 3. 4. 5. 4. 3. 2. 1. 0.]]
[[0. 1. 2. 3. 4. 5. 4. 3. 2. 1.]
 [1. 0. 1. 2. 3. 4. 5. 4. 3. 2.]
 [2. 1. 0. 1. 2. 3. 4. 5. 4. 3.]
 [3. 2. 1. 0. 1. 2. 3. 4. 5. 4.]
 [4. 3. 2. 1. 0. 1. 2. 3. 4. 5.]
 [5. 4. 3. 2. 1. 0. 1. 2. 3. 4.]
 [4. 5. 4. 3. 2. 1. 0. 1. 2. 3.]
 [3. 4. 5. 4. 3. 2. 1. 0. 1. 2.]
 [2. 3. 4. 5. 4. 3. 2. 1. 0. 1.]
 [1. 2. 3. 4. 5. 4. 3. 2. 1. 0.]]


In [84]:

print((precalcA==fullTestS).all())
print((fullTestS==precalcB).all())
print((fullTestS==precalcC).all())

True
True
True


In [24]:
out = np.array([[0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,4.000000,3.000000,2.000000,1.000000],
[1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,4.000000,3.000000,2.000000],
[2.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,4.000000,3.000000],
[3.000000,2.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,4.000000],
[4.000000,3.000000,2.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000],
[0.000000,4.000000,3.000000,2.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000],
[0.000000,0.000000,4.000000,3.000000,2.000000,1.000000,0.000000,0.000000,0.000000,0.000000],
[0.000000,0.000000,0.000000,4.000000,3.000000,2.000000,1.000000,0.000000,0.000000,0.000000],
[0.000000,0.000000,0.000000,0.000000,4.000000,3.000000,2.000000,1.000000,0.000000,0.000000],
[0.000000,0.000000,0.000000,0.000000,0.000000,4.000000,3.000000,2.000000,1.000000,0.000000]])

In [25]:
print(precalcA)
print(out)

[[0. 1. 2. 3. 4. 5. 4. 3. 2. 1.]
 [1. 0. 1. 2. 3. 4. 5. 4. 3. 2.]
 [2. 1. 0. 1. 2. 3. 4. 5. 4. 3.]
 [3. 2. 1. 0. 1. 2. 3. 4. 5. 4.]
 [4. 3. 2. 1. 0. 1. 2. 3. 4. 5.]
 [5. 4. 3. 2. 1. 0. 1. 2. 3. 4.]
 [4. 5. 4. 3. 2. 1. 0. 1. 2. 3.]
 [3. 4. 5. 4. 3. 2. 1. 0. 1. 2.]
 [2. 3. 4. 5. 4. 3. 2. 1. 0. 1.]
 [1. 2. 3. 4. 5. 4. 3. 2. 1. 0.]]
[[0. 0. 0. 0. 0. 5. 4. 3. 2. 1.]
 [1. 0. 0. 0. 0. 0. 5. 4. 3. 2.]
 [2. 1. 0. 0. 0. 0. 0. 5. 4. 3.]
 [3. 2. 1. 0. 0. 0. 0. 0. 5. 4.]
 [4. 3. 2. 1. 0. 0. 0. 0. 0. 5.]
 [0. 4. 3. 2. 1. 0. 0. 0. 0. 0.]
 [0. 0. 4. 3. 2. 1. 0. 0. 0. 0.]
 [0. 0. 0. 4. 3. 2. 1. 0. 0. 0.]
 [0. 0. 0. 0. 4. 3. 2. 1. 0. 0.]
 [0. 0. 0. 0. 0. 4. 3. 2. 1. 0.]]


In [19]:
print(np.array(precalcS))

out2 =np.array([ 0.000000,1.000000,2.000000,3.000000,4.000000,5.000000,4.000000,3.000000,2.000000,1.000000],dtype=int)
print(out2)

[0 1 2 3 4 5 4 3 2 1]
[0 1 2 3 4 5 4 3 2 1]
